# Generated by Django 3.0 on 2019-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
    ]
